### ISSUE TITLE
Detail Hotel Functionality

### ISSUE THREAD

**Issue by Izznakim** [Bangkit-C22-HO04/hotel-tvlk-mobile#20]
- [x] integrate detail with API
- [x] integrate review with API
- [x] redirect to review screen on text "More" click

**Comment by Izznakim** [comment]
@althof3 @Sasfort , ini review di detail page enaknya cuman nampilin 1 review doang atau berapa?

**Comment by althof3** [comment]
> @althof3 @Sasfort , ini review di detail page enaknya cuman nampilin 1 review doang atau berapa?

1 aja

**Comment by Izznakim** [comment]
> > @althof3 @Sasfort , ini review di detail page enaknya cuman nampilin 1 review doang atau berapa?
> 
> 1 aja

Oke
